- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop content
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Remove old app content"
  ansible.windows.win_file:
    path: /usr/share/nginx/html
    state: absent

- name: Create app directory
  ansible.windows.win_file:
    path: /usr/share/nginx/html
    state: directory

- name: Download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start Nginx
  ansible.builtin.systemd:
    state: restart
    name: nginx
    enabled: yes