#
#func_print_head "install python"
#dnf install python36 gcc python3-devel -y &>>$log_file
#func_status_check $?
#
#func_app_prereq
#
#func_print_head "install Python dependencies"
#pip3.6 install -r requirements.txt &>>$log_file
#func_status_check $?
#
#func_print_head "Update Passwords in system service file"
#sed -i -e "s|rabbitmq_appuser_password|${rabbitmq_appuser_password}|" ${script_path}/payment.service &>>$log_file
#func_status_check $?
#
#func_systemd_setup

- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: include app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: install python dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: include systemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
