#if [ "$schema_setup" == "mongo" ]; then
#func_print_head  "Copy mongodb"
#cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#func_status_check $?
#
#
#func_print_head  "Install mongodb"
#dnf install mongodb-org-shell -y &>>$log_file
#func_status_check $?
#
#
#func_print_head  "Load schema"
#mongo --host mongodb-dev.devopz1.online </app/schema/${component}.js &>>$log_file
#func_status_check $?
#
#fi
#if [ "$schema_setup" == "mysql" ]; then
#func_print_head "install mysql"
#dnf install mysql -y &>>$log_file
#func_status_check $?
#
#
#func_print_head "Load schema"
#mysql -h mysql-dev.devopz1.online -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>$log_file
#func_status_check $?
#fi

- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  ansible.builtin.shell: mongo --host  {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1') }} </app/schema/${component}.js